// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StajDefteri.Api.Data;

#nullable disable

namespace StajDefteri.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("StajDefteri.Api.Models.DefterKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RedAciklamasi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RedTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReddedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DefterKayitlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Durum = "bekliyor",
                            Icerik = "Proje kurulumu yapildi",
                            OgrenciId = 1,
                            Tarih = new DateOnly(2026, 7, 20)
                        },
                        new
                        {
                            Id = 2,
                            Durum = "onaylandi",
                            Icerik = "Login ekrani tamamlandi",
                            OgrenciId = 1,
                            Tarih = new DateOnly(2026, 7, 21)
                        },
                        new
                        {
                            Id = 3,
                            Durum = "bekliyor",
                            Icerik = "Veritabani semasi cizildi",
                            OgrenciId = 2,
                            Tarih = new DateOnly(2026, 7, 22)
                        });
                });

            modelBuilder.Entity("StajDefteri.Api.Models.IslemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IslemLoglari");
                });

            modelBuilder.Entity("StajDefteri.Api.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("YetkiliId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Batuhan",
                            Email = "ogrenci@test.com",
                            Rol = "ogrenci",
                            SifreHash = "$2a$11$bLvP3vhYl5kBk.kceeRUcup80fR1s022je218yJpE11uxNv.JXjDa",
                            YetkiliId = 3
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ayse",
                            Email = "ogrenci2@test.com",
                            Rol = "ogrenci",
                            SifreHash = "$2a$11$bLvP3vhYl5kBk.kceeRUcup80fR1s022je218yJpE11uxNv.JXjDa",
                            YetkiliId = 4
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Ahmet Hoca",
                            Email = "yetkili@test.com",
                            Rol = "yetkili",
                            SifreHash = "$2a$11$bLvP3vhYl5kBk.kceeRUcup80fR1s022je218yJpE11uxNv.JXjDa"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Zeynep Hoca",
                            Email = "yetkili2@test.com",
                            Rol = "yetkili",
                            SifreHash = "$2a$11$bLvP3vhYl5kBk.kceeRUcup80fR1s022je218yJpE11uxNv.JXjDa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
